### ISSUE TITLE
hung up on microsoft azure?

### ISSUE THREAD

**Issue by jimccann-rh** [Twingate-Labs/tg-ip-lookup#2]
[jimb0@fedora ~]$ python -c "exec(\"import tg_ip_lookup\ntg_ip_lookup.cloudlookup.loadCloudProviderData.main(\'*MaxMind License Key*\')\")"
Processing AWS ranges...
Processing GCP ranges...
Processing Azure ranges...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 2, in <module>
  File "/home/jimb0/.local/lib/python3.11/site-packages/tg_ip_lookup/cloudlookup/loadCloudProviderData.py", line 89, in main
    azure_public_info = load_networks(lookup_microsoft_download_url('https://www.microsoft.com/en-us/download/confirmation.aspx?id=56519'),
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jimb0/.local/lib/python3.11/site-packages/tg_ip_lookup/cloudlookup/loadCloudProviderData.py", line 63, in lookup_microsoft_download_url
    download_url = soup.find('a', {'data-bi-containername': 'download retry'})['href']
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
[jimb0@fedora ~]$

**Comment by jimccann-rh** [comment]
FYI I did put in my license key but did not want to show it on this portal

**Comment by emrul** [comment]
Hi @jimccann-rh - I've noticed this too and I think its because Microsoft have added code to detect automated downloads. As far as I can tell, they are the only cloud provider that make it difficult to programmatically download their IP ranges.

In any event, for now I've been able to work around the issue by replacing [this](https://github.com/Twingate-Labs/tg-ip-lookup/blob/73afa5775cb58785b563844e05c54cdaf75e4d81/cloudlookup/loadCloudProviderData.py#L60) line with the following:

```
    headers = {
        'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36'
    }
    page = requests.get(url, headers=headers)
```

However, I suppose I must come up with a more fool proof method.
